version: '3'

services:
  test-service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8001:8001"
    deploy:
      mode: replicated
      replicas: 1